# Day 9 — Practice

Quick review reps on boolean masking and `np.where()` before moving on to new NumPy topics (broadcasting, reshaping, combining arrays, sorting, `axis`).

Run the setup cell below first.

In [4]:
import numpy as np

test_scores = np.array([55, 80, 45, 90, 60, 70, 30])

## Exercise 1 — Combine three conditions

Write a function that returns only the scores that are between 50 and 85, **inclusive on both ends**.

In [3]:
def mid_range_scores(scores):
    """Return only scores between 50 and 85, inclusive on both ends."""
    return scores[(scores >= 50) & (scores <= 85)]

In [5]:
# Test cell
result = mid_range_scores(test_scores)
print(result)
assert list(result) == [55, 80, 60, 70], f"Expected [55, 80, 60, 70], got {list(result)}"
print("Passed!")

[55 80 60 70]
Passed!


## Exercise 2 — Label with three categories using `np.where()`

`np.where()` can be nested to handle more than two outcomes.

Write a function that labels each score:
- `'Fail'` if below 50
- `'Pass'` if between 50 and 74 (inclusive)
- `'Distinction'` if 75 or above

Hint: nest a second `np.where()` inside the `x` or `y` argument of the first one.

In [6]:
def label_scores(scores):
    """Label each score as 'Fail', 'Pass', or 'Distinction'."""
    return np.where(scores > 50, np.where((scores >= 50) & (scores <= 74), "Pass", 'Distinction'), "Fail")

In [7]:
# Test cell
result2 = label_scores(test_scores)
print(result2)
expected2 = ['Pass', 'Distinction', 'Fail', 'Distinction', 'Pass', 'Pass', 'Fail']
assert list(result2) == expected2, f"Expected {expected2}, got {list(result2)}"
print("Passed!")

['Pass' 'Distinction' 'Fail' 'Distinction' 'Pass' 'Pass' 'Fail']
Passed!


## Exercise 3 — Mask one array using another

So far the mask has come from the same array you're filtering. Now use a mask built from *one* array to filter a *different* array.

You're given `names` and `test_scores` (same length, matching by position). Write a function that returns the names of everyone who scored 60 or above.

In [10]:
names = np.array(['Amir', 'Bella', 'Carl', 'Dana', 'Eli', 'Farah', 'Gus'])

def high_scorers(names, scores, threshold):
    """Return the names of everyone whose score is >= threshold."""
    mask = scores >= threshold  
    return names[mask] 

In [11]:
# Test cell
result3 = high_scorers(names, test_scores, 60)
print(result3)
expected3 = ['Bella', 'Dana', 'Eli', 'Farah']
assert list(result3) == expected3, f"Expected {expected3}, got {list(result3)}"
print("Passed!")

['Bella' 'Dana' 'Eli' 'Farah']
Passed!


## Broadcasting

Broadcasting is how NumPy applies an operation between arrays of different shapes without you manually looping or resizing. You've already used a simple case: `temperatures > 15` stretches the scalar `15` across every element automatically.

### Exercise 4 — Scalar broadcasting

Given `prices`, write a function that returns all prices increased by 20% (i.e. multiplied by 1.2), rounded to the nearest whole number using `np.round()`.

In [14]:
prices = np.array([10, 20, 30, 40, 50])

def apply_price_increase(prices, percent):
    """Increase each price by the given percent (e.g. 20 means +20%), rounded to nearest whole number."""
    new_price = np.round(prices * 1.2)
    return new_price




In [15]:
# Test cell
result4 = apply_price_increase(prices, 20)
print(result4)
expected4 = [12.0, 24.0, 36.0, 48.0, 60.0]
assert list(result4) == expected4, f"Expected {expected4}, got {list(result4)}"
print("Passed!")

[12. 24. 36. 48. 60.]
Passed!


### Exercise 5 — Broadcasting a 1D array across a 2D array

`class_scores` below is a 2D array: each **row** is a student, each **column** is a test (Test 1, Test 2, Test 3).

`bonus_per_test` gives one bonus value per test (i.e. per column).

Write a function that adds the correct bonus to every student's score for each test, using broadcasting (no loops).

In [19]:
class_scores = np.array([
    [55, 60, 70],
    [80, 75, 65],
    [40, 50, 45]
])

bonus_per_test = np.array([5, 0, 10])

def apply_bonus(class_scores, bonus_per_test):
    """Add bonus_per_test to every row of class_scores using broadcasting."""

    return class_scores + bonus_per_test  

In [20]:
# Test cell
result5 = apply_bonus(class_scores, bonus_per_test)
print(result5)
expected5 = np.array([
    [60, 60, 80],
    [85, 75, 75],
    [45, 50, 55]
])
assert np.array_equal(result5, expected5), f"Expected {expected5.tolist()}, got {result5.tolist()}"
print("Passed!")

[[60 60 80]
 [85 75 75]
 [45 50 55]]
Passed!


### Exercise 6 — When broadcasting fails

Not every shape mismatch is broadcastable. Try running the cell below and read the error message — don't fix it, just read what NumPy tells you and jot down (in a comment or just to yourself) why it fails.

In [21]:
bad_bonus = np.array([5, 10])  # only 2 values, but class_scores has 3 columns

# Uncomment and run to see the error:
class_scores + bad_bonus

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 