# Day 8 — NumPy Fundamentals

## Concept 1: Arrays vs Python lists

A NumPy array looks similar to a list at first glance, but behaves very differently once you start doing math with it.

```python
my_list = [1, 2, 3, 4]
my_array = np.array([1, 2, 3, 4])
```

**The key difference — element-wise math:**

```python
my_list * 2      # [1, 2, 3, 4, 1, 2, 3, 4]  -- repeats the list!
my_array * 2     # [2, 4, 6, 8]              -- multiplies every element
```

With a plain Python list, `*` just repeats the list. With a NumPy array, `*` (and `+`, `-`, `/`, etc.) applies the operation to *every element* -- this is called **vectorization**, and it's the whole point of NumPy.

**Why it matters -- speed:** doing this with a list requires a loop (`[x * 2 for x in my_list]`). With NumPy you just write `my_array * 2` -- shorter, and genuinely faster for large data since NumPy runs the operation in optimized low-level code instead of looping in Python.

**Another key rule:** NumPy arrays hold **one data type** only (all ints, or all floats, etc.) -- unlike Python lists which can mix types freely. This is part of why NumPy is fast: knowing every element is the same type lets it use efficient memory storage and computation.

In [2]:
import numpy as np
import pandas as pd

## Exercise 1: Vectorized math

Write a function that takes a list of exam scores (out of 50) and returns a NumPy array with each score converted to a percentage (out of 100) -- i.e. each value doubled -- using array math, no loop.

In [3]:
scores_out_of_50 = [40, 35, 25, 48, 30]

In [11]:
def to_percentage(scores):
    """Take a list of scores out of 50 and return a NumPy array of
    percentages (out of 100), using vectorized math (no loop)."""
    scores = np.array(scores)
    return scores * 2

In [12]:
# Test cell
print(to_percentage(scores_out_of_50))

[80 70 50 96 60]


## Concept 2: Indexing and slicing

This works a lot like Python lists, with the same `[start:stop:step]` slicing rules:

```python
arr = np.array([10, 20, 30, 40, 50])
arr[0]        # 10 -- first element
arr[-1]       # 50 -- last element
arr[1:3]      # [20, 30] -- slice, stop index excluded
arr[:3]       # [10, 20, 30] -- from start up to index 3
arr[::2]      # [10, 30, 50] -- every 2nd element
```

For 2D arrays (like a grid/table of numbers), you index with `[row, column]`:

```python
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid[0, 1]    # 2 -- row 0, column 1
grid[1, :]    # [4, 5, 6] -- entire row 1
grid[:, 0]    # [1, 4] -- entire column 0
```

## Exercise 2: Slicing a 2D array

Given `grades_grid` below (rows = students, columns = 3 test scores each), write a function that returns **only the middle test's scores** (column index 1) for **all students**.

In [13]:
grades_grid = np.array([
    [80, 85, 90],
    [70, 75, 65],
    [60, 55, 70]
])

In [14]:
def middle_test_scores(grid):
    """Return column index 1 (the middle test) for all students."""

    return grid[1]

In [18]:
# Test cell
print(middle_test_scores(grades_grid))

[70 75 65]


## Concept 3: Boolean masking

This will feel very familiar -- it's the same idea as pandas filtering (`df[df["score"] > 50]`), because pandas filtering is actually built on this exact NumPy feature underneath.

```python
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25          # array([False, False, True, True, True])
arr[mask]                # array([30, 40, 50])
arr[arr > 25]             # same thing, written in one line
```

Just like pandas, you can combine conditions with `&` and `|`, and each condition needs parentheses:

```python
arr[(arr > 15) & (arr < 45)]   # array([20, 30, 40])
```

## Exercise 3: Filter with boolean masking

Given `temperatures` below, return only the values that are **above 15 and below 30** (a comfortable range), using boolean masking (no loop).

In [25]:
temperatures = np.array([5, 12, 18, 22, 27, 31, 35, 14, 20]) 

In [38]:
def comfortable_temps(temps):
    """Return only temperatures above 15 and below 30, using boolean masking."""
    mask = (temps > 15) & (temps < 30)
    return temps[mask] 

In [39]:
# Test cell
print(comfortable_temps(temperatures))

[18 22 27 20]


## Concept 4: Basic stats functions + `np.where`

NumPy has built-in stats functions that work directly on arrays:

```python
np.mean(arr)
np.std(arr)     # standard deviation
np.min(arr)
np.max(arr)
np.sum(arr)
```

`np.where()` is like an inline if/else applied across a whole array at once:

```python
np.where(arr > 25, "High", "Low")
# for each element: "High" if condition is True, else "Low"
```

This is the vectorized equivalent of writing a loop with an if/else inside it -- similar spirit to `.apply()` in pandas (like your `grade_by_score` function), but faster since it's built into NumPy directly instead of calling a Python function per row.

## Exercise 4: Mixed review -- stats + np.where

Using `test_scores` below:
1. Compute the mean score
2. Return a new array labeling each score `"Pass"` if it's greater than or equal to the mean, otherwise `"Fail"` -- using `np.where()`, no loop

In [40]:
test_scores = np.array([55, 80, 45, 90, 60, 70, 30])

In [43]:
def pass_fail_by_mean(scores):
    """Compute the mean, then return an array labeling each score
    'Pass' if >= mean, else 'Fail', using np.where()."""
    avg = np.mean(scores)
    return np.where(scores >= avg, "Pass", "Fail") 

In [44]:
# Test cell
print(pass_fail_by_mean(test_scores))

['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Fail']
