# Day 11 — Practice

Rounding out NumPy: reshaping, combining arrays, sorting, and the `axis` parameter.

Run the setup cell first.

In [1]:
import numpy as np

## Reshaping

`.reshape()` changes the *shape* of an array without changing its data or total number of elements. The new shape must hold the same total count — e.g. a 12-element array can become `(3, 4)`, `(4, 3)`, `(2, 6)`, `(6, 2)`, or `(2, 2, 3)`, but not `(3, 3)`.

```python
arr = np.arange(12)          # [0, 1, 2, ..., 11]
arr.reshape(3, 4)            # 3 rows, 4 columns
```

`.flatten()` does the reverse — collapses any shape back into 1D.

### Exercise 1 — Reshape

Write a function that takes a 1D array of exactly 12 elements and returns it reshaped into 3 rows and 4 columns.

In [2]:
def to_3x4(arr):
    """Reshape a 12-element 1D array into a 3x4 2D array."""
    return arr.reshape(3, 4)

In [3]:
# Test cell
data = np.arange(12)
result1 = to_3x4(data)
print(result1)
expected1 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
assert np.array_equal(result1, expected1), f"Expected {expected1.tolist()}, got {result1.tolist()}"
print("Passed!")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Passed!


## Combining arrays

- `np.concatenate([a, b])` joins arrays along an existing axis
- `np.vstack([a, b])` stacks arrays vertically (adds rows)
- `np.hstack([a, b])` stacks arrays horizontally (adds columns)

### Exercise 2 — Stack two classes together

You have scores from two class groups, each shaped `(rows=students, cols=tests)`. Write a function that stacks them vertically into one combined array (more students, same number of tests).

In [4]:
class_a = np.array([[55, 60], [80, 75]])
class_b = np.array([[40, 50], [90, 85]])

def combine_classes(class_a, class_b):
    """Stack two classes vertically into one array."""
    return np.vstack([class_a, class_b])

In [5]:
# Test cell
result2 = combine_classes(class_a, class_b)
print(result2)
expected2 = np.array([[55,60],[80,75],[40,50],[90,85]])
assert np.array_equal(result2, expected2), f"Expected {expected2.tolist()}, got {result2.tolist()}"
print("Passed!")

[[55 60]
 [80 75]
 [40 50]
 [90 85]]
Passed!


## Sorting

- `np.sort(arr)` returns a **sorted copy** of the values
- `np.argsort(arr)` returns the **indices** that would sort the array — useful when you need to sort one array based on another (like `names` based on `scores`)

### Exercise 3 — Sort names by score using `argsort`

Using `names` and `scores` below (matched by position), return the names sorted from **lowest to highest** score.

In [9]:
names = np.array(['Amir', 'Bella', 'Carl', 'Dana'])
scores = np.array([70, 55, 90, 60])

def names_sorted_by_score(names, scores):
    """Return names ordered from lowest to highest score."""
    order = np.argsort(scores) 
    return names[order]

In [10]:
# Test cell
result3 = names_sorted_by_score(names, scores)
print(result3)
expected3 = ['Bella', 'Dana', 'Amir', 'Carl']
assert list(result3) == expected3, f"Expected {expected3}, got {list(result3)}"
print("Passed!")

['Bella' 'Dana' 'Amir' 'Carl']
Passed!


## The `axis` parameter

On a 2D array, stats functions need to know *which direction* to collapse:
- `axis=0` → collapse **down the rows** (result: one value per column)
- `axis=1` → collapse **across the columns** (result: one value per row)

### Exercise 4 — Per-student and per-test averages

Using `class_scores` below (rows = students, columns = tests), write a function that returns **each student's average** (average across their tests).

In [19]:
class_scores = np.array([
    [55, 60, 70],
    [80, 75, 65],
    [40, 50, 45]
])

def student_averages(class_scores):
    """Return each student's average score across their tests."""
    avg = class_scores.mean(axis = 1)
    return avg 

In [20]:
# Test cell
result4 = student_averages(class_scores)
print(result4)
expected4 = np.array([61.66666667, 73.33333333, 45.0])
assert np.allclose(result4, expected4), f"Expected {expected4.tolist()}, got {result4.tolist()}"
print("Passed!")

[61.66666667 73.33333333 45.        ]
Passed!


### Exercise 5 — Per-test averages (the other axis)

Same `class_scores`. This time return **each test's average** (average down each column, across all students). Which `axis` do you need this time?

In [21]:
def test_averages(class_scores):
    """Return each test's average score across all students."""
    avg_per_test = class_scores.mean(axis = 0)
    return avg_per_test 

In [22]:
# Test cell
result5 = test_averages(class_scores)
print(result5)
expected5 = np.array([58.33333333, 61.66666667, 60.0])
assert np.allclose(result5, expected5), f"Expected {expected5.tolist()}, got {result5.tolist()}"
print("Passed!")

[58.33333333 61.66666667 60.        ]
Passed!
